version: "3"

services:
  web:
    build: .
    
    command: gunicorn inquiry_dashboard.wsgi:application --bind 0.0.0.0:8000
    
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
     # - POSTGRES_HOST_AUTH_METHOD: trust
    
      
volumes:
  postgres_data:
  static_volume:

