version: "3"

services:
  web:
    build: .
    
    command: gunicorn inquiry_dashboard.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/Inquiry/staticfiles
      - media_volume:/Inquiry/mediafiles
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
     # - POSTGRES_HOST_AUTH_METHOD: trust
    
  nginx:
    image: nginx:latest
    ports:
      - 88:88
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/Inquiry/staticfiles
      - media_volume:/Inquiry/mediafiles
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume:
  media_volume:

